name: Deno CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: setup deno
        uses: denolib/setup-deno@v2
      - name: deno version
        run: deno --version
      - name: install nodejs deps
        run: npm ci

      - name: run deno test
        run: npm run test:deno
